### ISSUE TITLE
ISSUE: As a fan I should be able to Delete my account

### ISSUE THREAD

**Issue by moorej2017** [CrouchJumpInc/fangagement-public#6]
Cannot delete acct. Pls let me out!

**Comment by hjames82** [comment]
same

**Comment by DrVonDevious** [comment]
I can't replicate this anymore. @hjames82 @moorej2017 can anyone confirm?

**Comment by hjames82** [comment]
Unable to confirm this because the app is unusable at this time.

**Comment by DrVonDevious** [comment]
Closing since this should work now but there is a new issue related to this #26

**Comment by ILikeConcerts** [comment]
I write "DELETE" as the pop up suggests but the red delete button still wont work for me when I click it. "Cancel" works though
